public class Main {
    public static void main(String[] args) {
        //SinglyLinkedList<Integer> singlyLinkedList = new SinglyLinkedList<>();
//        singlyLinkedList.add(8);
//        singlyLinkedList.add(null);
//        singlyLinkedList.add(9);
//        singlyLinkedList.add(10);
//        singlyLinkedList.add(11);
        //System.out.println(singlyLinkedList.contains(8));
        //System.out.println(singlyLinkedList.contains(null));
        //System.out.println(singlyLinkedList.remove(null));
//        System.out.println(singlyLinkedList.remove(Integer.valueOf(8)));
//        System.out.println(singlyLinkedList.remove(Integer.valueOf(5)));
        //System.out.println(singlyLinkedList);
        //System.out.println(singlyLinkedList.remove(4));
        //System.out.println(singlyLinkedList.remove(4));
//        System.out.println(singlyLinkedList.pop());
//        System.out.println(singlyLinkedList);
//        System.out.println(singlyLinkedList.pop());
//        System.out.println(singlyLinkedList);
//        DoublyLinkedList<Integer> doublyLinkedList = new DoublyLinkedList<>();
//        doublyLinkedList.add(4);
//        doublyLinkedList.add(5);
//        doublyLinkedList.add(1);
//        doublyLinkedList.add(6);
//        doublyLinkedList.add(7);
//        doublyLinkedList.add(8);
//        doublyLinkedList.add(9);
//        doublyLinkedList.add(10);
//        doublyLinkedList.add(11);
//        doublyLinkedList.add(12);
//        doublyLinkedList.add(13);
//        doublyLinkedList.add(14);
//        System.out.println(doublyLinkedList);
//        doublyLinkedList.remove(8);
//        doublyLinkedList.remove(11);
//        System.out.println(doublyLinkedList);
//        doublyLinkedList.removeAt(2);
//        doublyLinkedList.removeAt(8);
//        doublyLinkedList.add(20);
        //System.out.println(doublyLinkedList);
//        System.out.println(doublyLinkedList);
//        System.out.println(doublyLinkedList.pop());
//        System.out.println(doublyLinkedList.pop());
//        System.out.println(doublyLinkedList.contains(5));
//        MyArrayList<Integer> myArrayList = new MyArrayList<>();
//        myArrayList.add(5);
//        myArrayList.add(9);
//        myArrayList.add(null);
//        myArrayList.add(52);
//        myArrayList.add(9);
//        myArrayList.add(8);
//        System.out.println(myArrayList);
//        System.out.println(myArrayList.pop());
//        System.out.println(myArrayList);
//        System.out.println(myArrayList.pop());
//        System.out.println(myArrayList);
//        CircularLinkedList<Integer> circularLinkedList = new CircularLinkedList<>();
//        circularLinkedList.add(5);
//        circularLinkedList.add(6);
//        circularLinkedList.add(7);
//        circularLinkedList.add(8);
//        circularLinkedList.add(9);
//        circularLinkedList.add(null);
//        circularLinkedList.add(20);
//        circularLinkedList.add(18);
//        circularLinkedList.add(17);
//        System.out.println(circularLinkedList);
//        System.out.println(circularLinkedList.get(0));
//        System.out.println(circularLinkedList.get(6));
//        circularLinkedList.removeAt(1);
//        System.out.println(circularLinkedList);
//        circularLinkedList.removeAt(6);
//        System.out.println(circularLinkedList);
//        circularLinkedList.add(30);
//        System.out.println(circularLinkedList);
//       circularLinkedList.remove(6);
//        System.out.println(circularLinkedList);
//        circularLinkedList.remove(null);
//        circularLinkedList.remove(18);
//        circularLinkedList.remove(9);
//        System.out.println(circularLinkedList);
//        System.out.println(circularLinkedList.contains(38));
//        System.out.println(circularLinkedList.pop());
//        System.out.println(circularLinkedList.pop());
//        System.out.println(circularLinkedList);
//        System.out.println(circularLinkedList.size);
    }
}
